name: Strava Weekly Full Sync

on:
  schedule:
    # Run weekly on Sunday at 7 AM UTC
    - cron: '0 7 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  strava-full-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment variables
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        echo "Environment variables set"
        
    - name: Create tokens file from secrets
      env:
        STRAVA_TOKENS: ${{ secrets.STRAVA_TOKENS }}
      run: |
        echo "$STRAVA_TOKENS" > tokens.json
        
    - name: Run Strava pipeline (full sync)
      env:
        MAX_PAGES: 100  # Full sync
      run: |
        python -m strava_analytics.flows.main_pipeline
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: weekly-pipeline-logs
        path: logs/
        retention-days: 30
